apiVersion: v1
kind: Pod
metadata:
  name: trace-correlator
  namespace: monitoring
spec:
  restartPolicy: Never
  containers:
    - name: trace-correlator
      image: python:3.12-slim
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: scripts
          mountPath: /scripts
  volumes:
    - name: scripts
      configMap:
        name: trace-correlator-scripts
